- name: install desktop system
  package:
    name: task-xfce-desktop

- name: install desktop tools
  package:
    name: [firefox-esr, gnome-terminal, gedit, code, synaptic]

- name: configure systemd to graphical
  shell: systemctl set-default graphical.target
