---
- name: copy bash prompt for root
  copy:
    src: root/prompt.sh
    dest: /root/prompt.sh
    owner: root
    group: root
    mode: 0644

- name: copy gitconfig for root
  copy:
    src: root/gitconfig
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: 0644

- name: copy authorized_keys file
  copy:
    src: root/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0644

- name: create rsa ssh host key
  shell: "ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa"
  args:
    creates: /etc/ssh/ssh_host_rsa_key
  notify: restart sshd

- name: create ed25519 ssh host key
  shell: "ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -N '' -t ed25519"
  args:
    creates: /etc/ssh/ssh_host_ed25519_key
  notify: restart sshd

- name: create ecdsa key host (legacy)
  shell: "ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa"
  args:
    creates: /etc/ssh/ssh_host_ecdsa_key
  notify: restart sshd

- name: configure and secure openssh-server
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

- name: setup sudoers rules for training user
  template:
    src: etc/sudoers.d/99_training.j2
    dest: /etc/sudoers.d/99_training
    owner: root
    group: root
    mode: 0440

- name: configure vimrc for root
  copy:
    src: root/vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0644

