---
- name: copy bash prompt for root
  copy:
    src: root/prompt.sh
    dest: /root/prompt.sh
    owner: root
    group: root
    mode: 0644

- name: copy authorized_keys file
  copy:
    src: root/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0644

- name: configure and secure openssh-server
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

